# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: StagePipeline
    displayName: Stage from Pipeline
    jobs:
      - job: npminstall
        steps:
        - task: Npm@1
          inputs:
            command: 'install'
            
  - template: templates\azure-pipeline-stages-template.yml
    parameters:
      jobName: Linux
      vmImage: ubuntu-latest

  - template: templates\azure-pipeline-stages-template.yml
    parameters:
      jobName: Windows
      vmImage: windows-latest
